spring:
  rabbitmq:
    host: 10.12.14.155
    port: 5672
    username: guest
    password: guest

#admin的相关信息
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
