server:
  port: 9760

spring:
  application:
    name: config

  rabbitmq:
    host: 10.12.14.155
    port: 5672
    username: guest
    password: guest


# 注册中心配置
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 20   #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除(默认90秒)
    lease-renewal-interval-in-seconds: 5       #服务刷新时间配置，每隔这个时间会主动心跳一次(默认30秒)
  client:
    service-url:
      defaultZone: http://admin:zhupeng@localhost:9761/eureka/
    registry-fetch-interval-seconds: 10  #重新刷新服务地址的时间


#admin的相关信息
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
