server:
  port: 9765
spring:
  application:
    name: pc-user


  cloud:
    config:
      name: pc-user   #文件前缀名称
      discovery:
        enabled: true
        service-id: config  # 配置中心服务的名称
      profile: test  #git 文件的环境   例如 {name}-{profile} = service-gateway-dev.yml
      label: master
      enabled: true  #开启Config服务发现支持
      fail-fast: true  # 当config-server服务器宕机后，config-client将快速响应失败
    bus:
      refresh:
        enabled: true   #动态刷新配置
      #跟踪总线事件
      trace:
        enabled: true




# 注册中心配置
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 20   #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除(默认90秒)
    lease-renewal-interval-in-seconds: 5       #服务刷新时间配置，每隔这个时间会主动心跳一次(默认30秒)
  client:
    service-url:
      defaultZone: http://admin:zhupeng@localhost:9761/eureka/
    registry-fetch-interval-seconds: 10  #重新刷新服务地址的时间

#开启Hystrix
feign:
  hystrix:
    enabled: true

username: zhpeng222
